In [18]:
##反向传播求导 PytorchのAutograd
import torch as t
from torch.autograd import Variable

In [19]:
x=Variable(t.ones(2,2),requires_grad=True)
x


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [21]:
y=x.sum()
y

tensor(4., grad_fn=<SumBackward0>)

In [23]:
y.grad_fn

In [42]:
#y=x.sum()=(x[0][0]+x[0][1]+x[1][0]+x[1][1])
#每个梯度=1
#反向传播过程之中梯度是累加的(accumulated)
x.grad.data.zero_()
y.backward()
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [53]:
#Variable 与Tensor 借口一致 无缝切换
x=Variable(t.ones(5,4))
y=t.ones(5,4)
x+y
z=t.cos(x)
print('x.data=',x.data)
x_tensor_cos=t.cos(x.data)
print(x_tensor_cos)

x.data= tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403]])
