In [127]:
##begin
from __future__ import print_function
import torch as t

##从接口角度可分为两类
##tensor.function  & torch.function

##add 与 add_的区别


In [128]:
##创建tensor
a=t.Tensor(2,3) #指定形状, 去值与内存状态有关
print(a)

b=t.Tensor([[2,3,4],[1,3,4]])
# print(b)
b
b.tolist()

b_size=b.size()
b_size
b.numel()

#创建与b相同形状的tensor
c=t.Tensor(b.size())
c
c.shape
d0=t.Tensor(2,3)
d=t.Tensor([2,3])
d2=t.Tensor((2,3))
print(d0)
print(d)
print(d2)

##其余创建Tensor的方法
print(t.zeros(2,3),
     t.arange(1,6,3),
     t.ones(2,3),
     t.linspace(1,22,3),
     t.randn(1,4),
     t.rand(1,4),
     t.randperm(5) ,#长度为5的随机数列,
     t.eye(2,3))

##测试格式化
fate=('saber','lancer','archor','assassin','caster','berserker','rider')
# print(fate[i] for i in range(7))
for i in range(7):
    print(fate[i],'\n')
print('\n'.join('%-11s' %fate[i] for i in range(7)))

print('%10s'%('fate'))

tensor([[-5.0193e-11,  3.0871e-41,  1.4013e-45],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[-1.1791e-10,  3.0871e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([2., 3.])
tensor([2., 3.])
tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([1, 4]) tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([ 1.0000, 11.5000, 22.0000]) tensor([[-0.3543, -2.2540,  0.3998,  0.3763]]) tensor([[0.9474, 0.1344, 0.0046, 0.3967]]) tensor([1, 2, 3, 0, 4]) tensor([[1., 0., 0.],
        [0., 1., 0.]])
saber 

lancer 

archor 

assassin 

caster 

berserker 

rider 

saber      
lancer     
archor     
assassin   
caster     
berserker  
rider      
      fate


In [157]:
##常规Tensor操作
#tensor.view 重整Ｔｅｎｓｏｒ形状，但共享内存
#squeeze与unsqueeze减 增维度
# a=t.Tensor(2,3)
a=t.arange(0,6)
a.view(-1,3)
a0=t.Tensor(2,3)
print(a.size())
print((a0.size()))

a0.unsqueeze(1)
a0
# print(t.Tensor.squeeze(a,0))

c=t.arange(0,27).view(3,3,3)
c1=t.arange(0,27).view(-1,3,3)
c1.squeeze()
c1

torch.Size([6])
torch.Size([2, 3])


tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])